import { DemoProject, ServiceItem, PricingPlan } from './types';

export const AGENCY_DETAILS = {
  name: 'Website Creation Agency',
  email: 'sudhanshuyadav82400@gmail.com',
  tagline: 'WEB STUDIO',
  heroHeading: 'Professional Websites. Built for Your Business.',
  heroSubheading:
    'Modern, fast and mobile-friendly websites designed to give your business a strong online presence.',
  footerDescription:
    'Professional websites built for businesses that want to grow online.',
};

export const SERVICES: ServiceItem[] = [
  {
    id: 'business-websites',
    title: 'Business Websites',
    description: 'Modern websites for local businesses and companies.',
    features: [
      'Clean corporate branding',
      'Services and about showcase',
      'Lead capture & inquiry routing',
      'Search engine friendly structure',
    ],
    iconName: 'Building2',
  },
  {
    id: 'landing-pages',
    title: 'Landing Pages',
    description: 'High-converting landing pages for products, services and campaigns.',
    features: [
      'Conversion-focused architecture',
      'Compelling call-to-action sections',
      'Fast loading speed',
      'Optimized for advertising campaigns',
    ],
    iconName: 'Rocket',
  },
  {
    id: 'ecommerce-websites',
    title: 'E-commerce Websites',
    description: 'Professional online stores with a clean shopping experience.',
    features: [
      'Product catalog & filtering',
      'Secure checkout flows',
      'Inventory & order management',
      'Mobile-optimized shopping cart',
    ],
    iconName: 'ShoppingBag',
  },
  {
    id: 'mobile-friendly-design',
    title: 'Mobile-Friendly Design',
    description: 'Websites that work smoothly on phones, tablets and desktops.',
    features: [
      'Responsive across all screen sizes',
      'Touch-friendly interactive elements',
      'Adaptive image scaling',
      'Smooth browsing experience',
    ],
    iconName: 'Smartphone',
  },
  {
    id: 'website-redesign',
    title: 'Website Redesign',
    description: 'Modernize outdated websites and improve their user experience.',
    features: [
      'Modern visual upgrade',
      'Improved navigation and speed',
      'Mobile optimization update',
      'Better engagement & retention',
    ],
    iconName: 'RefreshCw',
  },
  {
    id: 'custom-web-solutions',
    title: 'Custom Web Solutions',
    description: "Custom website functionality based on the client's requirements.",
    features: [
      'Tailored interactive workflows',
      'API & third-party integrations',
      'Custom form automations',
      'Scalable frontend architectures',
    ],
    iconName: 'Cpu',
  },
];

export const DEMO_PROJECTS: DemoProject[] = [
  {
    id: 'demo-business',
    title: 'Corporate Advisory & Law Group',
    category: 'Business Website',
    categoryLabel: 'Business Website',
    summary: 'A clean, authoritative corporate website built to highlight consultation services, attorney practice areas, and direct email inquiries.',
    badge: 'Demo Project',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Corporate business website mockup on high resolution screen',
    features: ['Practice Area Directory', 'Consultation Request Flow', 'Speed Score 99/100', 'Executive Profiles'],
    techStack: ['React', 'Tailwind CSS', 'Vite', 'Node.js'],
    accentColor: '#1e40af',
    highlights: [
      { label: 'Load Time', val: '0.8s' },
      { label: 'Responsive', val: '100%' },
      { label: 'SEO Score', val: '98/100' },
    ],
  },
  {
    id: 'demo-restaurant',
    title: 'Botanical Table & Artisanal Bistro',
    category: 'Restaurant Website',
    categoryLabel: 'Restaurant Website',
    summary: 'A sensory culinary presentation featuring interactive seasonal menus, chef story, dining ambience gallery, and table reservation request form.',
    badge: 'Demo Project',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Botanical restaurant and dining website layout preview',
    features: ['Interactive Seasonal Menu', 'Reservation Request Form', 'Curated Photo Gallery', 'Dietary Filter Tags'],
    techStack: ['React', 'Modern CSS Grid', 'Motion'],
    accentColor: '#7c3aed',
    highlights: [
      { label: 'Menu Clicks', val: '+45%' },
      { label: 'Mobile Optimized', val: 'Yes' },
      { label: 'Accessibility', val: 'AA Grade' },
    ],
  },
  {
    id: 'demo-dental',
    title: 'Modern Smile & Dental Clinic',
    category: 'Dental Clinic Website',
    categoryLabel: 'Dental Clinic Website',
    summary: 'A calming and trustworthy clinic website designed for patient peace of mind, treatment guides, doctor credentials, and clean appointment requests.',
    badge: 'Demo Project',
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Modern dental and healthcare clinic website presentation',
    features: ['Treatment Breakdown', 'Online Appointment Booking Flow', 'Before & After Showcase', 'Doctor Credentials'],
    techStack: ['React', 'Tailwind CSS', 'Form Validation'],
    accentColor: '#0284c7',
    highlights: [
      { label: 'Appointment Forms', val: 'Instant' },
      { label: 'Patient Retention', val: 'High' },
      { label: 'Google Maps Link', val: 'Integrated' },
    ],
  },
  {
    id: 'demo-ecommerce',
    title: 'Aura Lifestyle & Living Store',
    category: 'E-commerce Website',
    categoryLabel: 'E-commerce Website',
    summary: 'An elegant e-commerce experience showcasing handcrafted goods, product variations, real-time cart review, and seamless checkout design.',
    badge: 'Demo Project',
    imageUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Minimalist artisan e-commerce online store interface',
    features: ['Product Quick View', 'Real-time Cart Drawer', 'Category Filter Matrix', 'Secure Checkout Flow'],
    techStack: ['React', 'Tailwind', 'E-commerce Architecture'],
    accentColor: '#4f46e5',
    highlights: [
      { label: 'Cart Speed', val: '< 0.5s' },
      { label: 'Conversion Design', val: 'Optimized' },
      { label: 'Device Support', val: 'Universal' },
    ],
  },
  {
    id: 'demo-service',
    title: 'PrimeTech Field & Facility Services',
    category: 'Service Business Website',
    categoryLabel: 'Service Business Website',
    summary: 'A direct, professional website created for commercial maintenance and inspection contractors with instant service quote requests.',
    badge: 'Demo Project',
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Professional facility and field service business website',
    features: ['Service Area Coverage', 'Multi-tier Service Breakdown', 'Instant Estimate Calculator', 'Quality Guarantee'],
    techStack: ['React', 'Interactive Calculator', 'Tailwind'],
    accentColor: '#2563eb',
    highlights: [
      { label: 'Inquiry Rate', val: 'High' },
      { label: 'Page Speed', val: '100/100' },
      { label: 'Architecture', val: 'Modern' },
    ],
  },
  {
    id: 'demo-landing',
    title: 'NextPulse Analytics Platform',
    category: 'Modern Landing Page',
    categoryLabel: 'Modern Landing Page',
    summary: 'A high-impact, conversion-engineered SaaS landing page highlighting interactive metric dashboards, customer benefits, and rapid signup calls to action.',
    badge: 'Demo Project',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Modern high-converting SaaS landing page with analytics interface',
    features: ['Hero Interactive Preview', 'Dynamic Feature Tabs', 'Social Proof Grid', 'Fast Signup Funnel'],
    techStack: ['React', 'Motion', 'Tailwind CSS'],
    accentColor: '#9333ea',
    highlights: [
      { label: 'Bounce Rate', val: 'Low' },
      { label: 'Conversion Focused', val: 'Yes' },
      { label: 'Animation', val: '60fps' },
    ],
  },
];

export const PROCESS_STEPS = [
  {
    step: '01',
    title: 'Tell Us About Your Business',
    description: 'Share your goals, target audience, and preferred design vision with us through our streamlined project questionnaire.',
    icon: 'MessageSquareText',
  },
  {
    step: '02',
    title: 'We Plan Your Website',
    description: 'We map out your site architecture, wireframe essential page layouts, and select the optimal technology stack.',
    icon: 'Compass',
  },
  {
    step: '03',
    title: 'We Design & Build',
    description: 'We construct your website from scratch with clean typography, responsive layouts, fast loading speeds, and robust forms.',
    icon: 'Code2',
  },
  {
    step: '04',
    title: 'Launch Your Website',
    description: 'After thorough quality assurance, speed optimization, and responsive testing, your website is launched to the world.',
    icon: 'Rocket',
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    name: 'Starter',
    price: '₹12,000',
    description: 'Ideal for local businesses and professionals establishing their core digital identity.',
    features: [
      'Professional website',
      'Mobile responsive design',
      'Up to 5 pages',
      'Contact form',
      'Basic SEO setup',
      'Fast performance',
    ],
    highlighted: false,
  },
  {
    name: 'Business',
    price: '₹18,000',
    badge: 'Most Popular',
    description: 'Perfect for growing businesses seeking expanded pages, advanced aesthetics, and lead optimization.',
    features: [
      'Everything in Starter',
      'Up to 10 pages',
      'Advanced design',
      'Custom sections',
      'Lead/contact forms',
      'SEO optimization',
      'Priority support',
    ],
    highlighted: true,
  },
  {
    name: 'Premium',
    price: 'Custom Quote',
    description: 'Tailored for organizations requiring custom web architecture, e-commerce, or specialized workflows.',
    features: [
      'Custom website',
      'Advanced functionality',
      'Custom integrations',
      'E-commerce or advanced features',
      'Custom requirements',
      'Personalized quote',
    ],
    highlighted: false,
  },
];

export const QUESTIONNAIRE_OPTIONS = {
  websiteTypes: [
    'Business Website',
    'Landing Page',
    'E-commerce',
    'Portfolio',
    'Restaurant',
    'Dental Clinic',
    'Service Business',
    'Other',
  ],
  numberOfPages: ['1–3', '4–5', '6–10', '10+'],
  requiredFeatures: [
    'Contact Form',
    'Booking Form',
    'WhatsApp Link',
    'Social Media Integration',
    'Gallery',
    'Blog',
    'E-commerce',
    'Payment Integration',
    'Google Maps',
    'Custom Features',
  ],
  estimatedBudgets: [
    '₹5,000 – ₹10,000',
    '₹10,000 – ₹15,000',
    '₹15,000 – ₹20,000',
    '₹20,000 – ₹30,000',
    '₹30,000 – ₹50,000',
    '₹50,000+',
    'Custom Budget',
  ],
  targetLaunchSchedules: [
    'ASAP',
    'Within 1 Week',
    '1–2 Weeks',
    '2–4 Weeks',
    'Flexible',
  ],
};
